---
type: showroom

# Set the left column width to 30%
default_width: 30
# Persist the URL state so browser refresh doesn't reset the UI
persist_url_state: true

tabs:
  - name: AAP Controller
    url: 'https://${USER}-aap-${USER}-aap.${DOMAIN}'
  - name: Self-Service Portal
    url: 'https://self-service-rhaap-portal-${USER}-aap-ssap.${DOMAIN}'
  - name: OCP Console
    url: 'https://console-openshift-console.${DOMAIN}'
